# Input files
obs_flow: "/home/jsadler/drb_data/obs_flow_full_raw"
obs_temp: "/home/jsadler/drb_data/obs_temp_full"
sntemp_file: "/home/jsadler/drb_data/uncal_sntemp_input_output"
#catchment_attr: "/home/jsadler/drb_data/seg_attr_drb.feather"
dist_matrix: "/home/jsadler/drb_data/distance_matrix.npz"

out_dir: "/caldera/projects/usgs/water/iidd/datasci/drb_ml_model/alison_run/all_inputs"
code_dir: "/home/jsadler/river-dl/river_dl"

x_vars: ['seg_ccov', 'seg_elev', 'seg_humid', 'seg_length', 'seg_rain', 'seg_shade', 'seg_slope', 'seg_tave_air', 'seg_tave_gw', 'seg_tave_sroff', 'seg_tave_ss', 'seg_tave_upstream', 'seg_upstream_inflow', 'seg_width', 'seginc_gwflow', 'seginc_potet', 'seginc_sroff', 'seginc_ssflow', 'seginc_swrad']

primary_variable: "flow"
lamb: 0
hidden_size: 20

train_start_date:
  - '1985-10-01'
train_end_date:
  - '2006-09-30'
val_start_date: '2006-10-01'
val_end_date: '2010-09-30'
test_start_date:
  - '2010-10-01'
test_end_date:
  - '2021-09-30'

pt_epochs: 200
ft_epochs: 100
